on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk

    steps:
      - name: Checkout Dolphin
        uses: actions/checkout@v3
        with:
          path: dolphin
          submodules: recursive
      
      - name: Checkout Qt
        uses: actions/checkout@v3
        with:
          repository: dolphin-emu/ext-steam-runtime-qt
          path: qt
      
      - name: Restore Build Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            build/*
            !build/Binaries
            ccache/*
          key: build-linux
      
      #- name: Install SSH Client
      #  run: |
      #    apt install -y openssh-client
      
      #- name: Start Upterm Session
      #  uses: mxschmitt/action-tmate@v3

      - name: Install ccache
        run: |
          apt install -y ccache

      - name: Set CCACHE_DIR
        run: |
          mkdir -p ccache
          echo "CCACHE_DIR=$PWD/ccache" >> $GITHUB_ENV

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake ../dolphin -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_PREFIX_PATH=$PWD/../qt/latest/amd64 -DSTEAM=ON -DENABLE_AUTOUPDATE=OFF -DENABLE_EVDEV=OFF -DENABLE_LLVM=OFF -DENABLE_SDL=ON
      
      - name: Build
        run: |
          cd build
          ninja
      
      - name: Save Build Cache
        uses: actions/cache/save@v3
        with:
          path: |
            build/*
            !build/Binaries
            ccache/*
          key: build-linux
